site_name: JupyterHub-Deployment-CombOpt
dev_addr: 127.0.0.1:8001

theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  palette:
    primary: 'lime'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'build'
  favicon: 'assets/images/baseline-build-24px.ico'

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc
  - pymdownx.smartsymbols
repo_url: https://github.com/michael-ritter/jupyterhub-combopt-ma4502
extra_css: 
    - static/css/toc.css
copyright: 'Copyright &copy; 2019 Peter D. Kazarinoff, Michael Ritter'

nav:
  - Home: index.md
  - What is JupyterHub?: what_is_jupyterhub.md
  - Set Up and Tools: setup_and_tools.md
  - SSH Keys: ssh_keys.md
  - Server Setup: server_setup.md
  - Install JupyterHub: install_jupyterhub.md
  - Install Nginx: nginx_install.md
  - SSL Certificates: ssl_certificates.md
  - Cookie Secret and Proxy Auth Token: cookie_secret_proxy_auth_token.md
  - Nginx Configuration: nginx_config.md
  - JupyterHub Configuration: jupyterhub_config.md
  - System Service: systemd.md
  - Add Users: add_users.md
  - Add Imprint and Privacy Statement: imprint_privacy.md
  - GitLab OAuth: gitlab_oauth.md
  #- Google OAuth: google_oauth.md
  # - Custom Login Page: custom_login_page.md
  - Assignments on GitHub: assignments_on_github.md
  - nbgitpuller Plugin: nbgitpuller_plugin.md
  - Extra Configuration: extra_configuration.md
  - Periodic Maintenance: periodic_maintenance.md
  - Shutdown: shutdown.md
  - Optional Extras:
      - JupyterLab Default Interface: jupyterlab_default_interface.md
      - Gurobi Installation: gurobi.md
      - Draw.IO extension: draw_dot_IO_extension.md
      - GitHub Extension for JupyterLab: github_extension.md
      - Building the Docs: building_docs.md
  - Useful Commands: useful_commands.md
